BEGIN;

SET LOCAL search_path TO fault_management, public;

CREATE TABLE IF NOT EXISTS email_outbox (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    fault_id          bigint REFERENCES faults(id) ON DELETE RESTRICT,
    notification_type varchar(50) NOT NULL,
    recipient_email   varchar(254) NOT NULL,
    recipient_name    varchar(200) NOT NULL,
    subject           varchar(300) NOT NULL,
    html_body         text NOT NULL,
    status            varchar(20) NOT NULL DEFAULT 'PENDING',
    retry_count       integer NOT NULL DEFAULT 0,
    next_retry_at     timestamptz,
    last_error        varchar(2000),
    created_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    sent_at           timestamptz,
    CONSTRAINT ck_email_outbox_status CHECK
        (status IN ('PENDING', 'PROCESSING', 'RETRY', 'SENT', 'FAILED')),
    CONSTRAINT ck_email_outbox_retry_count CHECK (retry_count BETWEEN 0 AND 5),
    CONSTRAINT ck_email_outbox_sent_state CHECK
        ((status = 'SENT' AND sent_at IS NOT NULL) OR status <> 'SENT')
);

CREATE INDEX IF NOT EXISTS ix_email_outbox_delivery_queue
    ON email_outbox (status, next_retry_at, created_at)
    WHERE status IN ('PENDING', 'RETRY');

CREATE INDEX IF NOT EXISTS ix_email_outbox_user_created
    ON email_outbox (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_email_outbox_fault
    ON email_outbox (fault_id)
    WHERE fault_id IS NOT NULL;

GRANT SELECT, INSERT, UPDATE ON email_outbox TO iett_fault_app;
GRANT USAGE, SELECT ON SEQUENCE email_outbox_id_seq TO iett_fault_app;

COMMIT;

