import 'bootstrap/dist/js/bootstrap.bundle.min.js';import 'bootstrap-icons/font/bootstrap-icons.css';import 'admin-lte/dist/css/adminlte.min.css';import 'admin-lte';import { Modal } from 'bootstrap';import Swal from 'sweetalert2';import { authService } from '../auth/auth-service.js';import { inspectionsApi } from '../api/inspections-api.js';import { renderNavigation } from '../ui/navigation.js';import { translateDisplayText, translateDisplayValue } from '../ui/turkish-display.js';import '../styles/app.css';
let inspections=[];let inspectionQueue=[];let user=null;const createModal=new Modal('#create-modal');const typeNames={POST_REPAIR:'Tamir sonrası',TEST_DRIVE:'Test sürüşü',RETURN_TO_SERVICE:'Servise dönüş'};const resultNames={PASSED:['Başarılı','success'],FAILED:['Başarısız','danger'],CONDITIONAL:['Koşullu','warning'],PENDING:['Bekliyor','secondary']};const dateFormat=new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short'});

// Kontrol bekleyen arızaları geçmiş kontrol kayıtlarından ayrı gösterir.
// Böylece yetkili hangi aracı kontrol etmesi gerektiğini arıza ID'si aramadan görür.
function renderInspectionQueue(){const body=document.querySelector('#inspection-queue-body');document.querySelector('#queue-count').textContent=inspectionQueue.length;body.replaceChildren();inspectionQueue.forEach(item=>{const row=document.createElement('tr');const waiting=item.waitingSince?dateFormat.format(new Date(item.waitingSince)):'-';row.innerHTML=`<td><strong>${item.faultNumber}</strong><div class="small text-warning">Kontrol zorunlu</div></td><td><strong>${item.vehicle.doorNumber}</strong><div class="small text-secondary">${item.vehicle.plate} · ${item.vehicle.currentMileage.toLocaleString('tr-TR')} km</div></td><td>${item.garage}</td><td>${item.category}</td><td><span class="badge text-bg-success">${translateDisplayValue(item.repairResult,'Tamir tamamlandı')}</span></td><td>${waiting}<div class="small text-secondary">Deneme ${item.attempt+1}/${item.maxAttempts}</div></td><td><button class="btn btn-warning btn-sm inspect-queued" data-fault-id="${item.faultId}"><i class="bi bi-clipboard-check me-1"></i>Kontrol Et</button></td>`;body.appendChild(row);});if(!inspectionQueue.length)body.innerHTML='<tr><td colspan="7" class="text-center text-secondary py-4">Kontrol bekleyen araç bulunmuyor.</td></tr>';}

// Kuyruktaki "Kontrol Et" düğmesi araç, kilometre, arıza ve kontrol türünü
// otomatik doldurur; kullanıcıdan yalnızca gerçek kontrol sonucunu ister.
function openQueuedInspection(faultId){const item=inspectionQueue.find(x=>x.faultId===faultId);if(!item)return;const form=document.querySelector('#create-form');form.reset();const vehicleSelect=document.querySelector('#vehicle-select');vehicleSelect.replaceChildren(new Option(`${item.vehicle.doorNumber} · ${item.vehicle.plate} · ${item.garage}`,item.vehicle.id,true,true));form.elements.inspectionType.value='POST_REPAIR';form.elements.faultId.value=item.faultId;form.elements.odometer.value=item.vehicle.currentMileage;document.querySelector('#vehicle-search').value=item.vehicle.doorNumber;createModal.show();}
// Geçmiş kontroller arama ve sonuç ölçütlerine göre tarayıcıda filtrelenir.
function render(){const search=document.querySelector('#search').value.toLocaleLowerCase('tr-TR');const result=document.querySelector('#result-filter').value;const items=inspections.filter(x=>(!result||x.result===result)&&`${x.vehicle.doorNumber} ${x.vehicle.plate} ${x.vehicle.garage} ${x.faultNumber??''}`.toLocaleLowerCase('tr-TR').includes(search));document.querySelector('#total').textContent=items.length;document.querySelector('#passed').textContent=items.filter(x=>x.result==='PASSED').length;document.querySelector('#failed').textContent=items.filter(x=>x.result==='FAILED').length;document.querySelector('#pending').textContent=items.filter(x=>['PENDING','CONDITIONAL'].includes(x.result)).length;const body=document.querySelector('#inspection-body');body.replaceChildren();items.forEach(x=>{const [text,color]=resultNames[x.result]??[translateDisplayValue(x.result),'secondary'];const row=document.createElement('tr');row.innerHTML=`<td class="text-nowrap">${dateFormat.format(new Date(x.inspectedAt??x.createdAt))}</td><td><strong>${x.vehicle.doorNumber}</strong><div class="small text-secondary">${x.vehicle.plate}</div></td><td>${x.vehicle.garage}</td><td>${typeNames[x.inspectionType]??translateDisplayValue(x.inspectionType)}</td><td><span class="badge text-bg-${color}">${text}</span></td><td>${x.odometer?.toLocaleString('tr-TR')??'-'}</td><td>${x.faultNumber??'-'}</td><td>${x.inspector?`${x.inspector.fullName}<div class="small text-secondary">${x.inspector.personnelNumber}</div>`:'-'}</td><td>${translateDisplayText(x.nextAction)}</td>`;body.appendChild(row);});if(!items.length)body.innerHTML='<tr><td colspan="9" class="text-center text-secondary py-5">Kontrol kaydı bulunamadı.</td></tr>';}
// Araç araması gecikmeli çalışarak her tuşta gereksiz API isteği oluşmasını azaltır.
let searchTimer;async function searchVehicles(){clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{try{const vehicles=await inspectionsApi.searchVehicles(document.querySelector('#vehicle-search').value);const select=document.querySelector('#vehicle-select');select.replaceChildren(new Option('Araç seçin',''));vehicles.forEach(x=>select.appendChild(new Option(`${x.doorNumber} · ${x.plate} · ${x.garage} · ${x.currentMileage.toLocaleString('tr-TR')} km`,x.id)));}catch(error){Swal.fire({icon:'error',title:'Araçlar getirilemedi',text:error.message});}},300);}
async function initialize(){try{user=await authService.requireAuthenticatedUser();if(!user)return;document.querySelector('#current-user').textContent=`${user.fullName} · ${user.role}`;renderNavigation('inspections',user.role);[inspections,inspectionQueue]=await Promise.all([inspectionsApi.getAll(),inspectionsApi.getQueue()]);render();renderInspectionQueue();document.querySelector('#table-container').classList.remove('d-none');}catch(error){const box=document.querySelector('#page-error');box.textContent=error.message;box.classList.remove('d-none');}finally{document.querySelector('#loading').classList.add('d-none');}}
document.querySelector('#search').addEventListener('input',render);document.querySelector('#result-filter').addEventListener('change',render);document.querySelector('#vehicle-search').addEventListener('input',searchVehicles);document.querySelector('#inspection-queue-body').addEventListener('click',event=>{const button=event.target.closest('.inspect-queued');if(button)openQueuedInspection(Number(button.dataset.faultId));});document.querySelector('#create-button').addEventListener('click',()=>{createModal.show();searchVehicles();});document.querySelector('#create-form').addEventListener('submit',async event=>{event.preventDefault();const formElement=event.currentTarget;const raw=Object.fromEntries(new FormData(formElement));const payload={...raw,vehicleId:Number(raw.vehicleId),faultId:raw.faultId?Number(raw.faultId):null,odometer:raw.odometer?Number(raw.odometer):null};try{await inspectionsApi.create(payload);createModal.hide();await Swal.fire({icon:'success',title:'Kontrol kaydedildi'});[inspections,inspectionQueue]=await Promise.all([inspectionsApi.getAll(),inspectionsApi.getQueue()]);render();renderInspectionQueue();formElement.reset();}catch(error){Swal.fire({icon:'error',title:'Kayıt oluşturulamadı',text:error.message});}});document.querySelector('#logout-button').addEventListener('click',()=>authService.logout());initialize();
