import 'bootstrap/dist/js/bootstrap.bundle.min.js'; import 'bootstrap-icons/font/bootstrap-icons.css'; import 'admin-lte/dist/css/adminlte.min.css'; import 'admin-lte';
import { Modal } from 'bootstrap'; import Swal from 'sweetalert2'; import { authService } from '../auth/auth-service.js'; import { garagesApi } from '../api/garages-api.js'; import { techniciansApi } from '../api/technicians-api.js'; import { renderNavigation } from '../ui/navigation.js'; import { translateDisplayValue } from '../ui/turkish-display.js'; import '../styles/app.css';

let technicians=[]; let teams=[]; let user=null; const createModal=new Modal('#create-modal');
// Metin ve garaj filtresi personel tablosunu ve üstteki ekip özet sayaçlarını birlikte günceller.
function render(){const garage=document.querySelector('#garage-filter').value;const search=document.querySelector('#search').value.toLocaleLowerCase('tr-TR');const visibleTeams=teams.filter(x=>!garage||String(x.garageId)===garage);const visible=technicians.filter(x=>(!garage||String(x.garage.id)===garage)&&`${x.personnelNumber} ${x.firstName} ${x.lastName}`.toLocaleLowerCase('tr-TR').includes(search));document.querySelector('#team-total').textContent=visibleTeams.filter(x=>x.isActive).length;document.querySelector('#team-available').textContent=visibleTeams.filter(x=>x.isActive&&x.isAvailable).length;document.querySelector('#technician-total').textContent=visible.filter(x=>x.isActive).length;document.querySelector('#fault-total').textContent=visibleTeams.reduce((sum,x)=>sum+x.activeFaultCount,0);const body=document.querySelector('#technician-body');body.replaceChildren();visible.forEach(x=>{const row=document.createElement('tr');row.innerHTML=`<td class="fw-semibold">${x.personnelNumber}</td><td>${x.firstName} ${x.lastName}</td><td>${x.garage.name}</td><td>${x.team.name}</td><td>${x.isTeamLeader?'Ekip lideri':'Teknisyen'}</td><td><span class="badge text-bg-${x.workStatus==='AVAILABLE'?'success':'warning'}">${translateDisplayValue(x.workStatus)}</span></td><td><span class="badge text-bg-${x.isActive?'success':'secondary'}">${x.isActive?'Aktif':'Pasif'}</span></td><td><button class="btn btn-outline-${x.isActive?'danger':'success'} btn-sm" data-toggle="${x.id}">${x.isActive?'Pasife al':'Aktifleştir'}</button></td>`;body.appendChild(row);});if(!visible.length)body.innerHTML='<tr><td colspan="8" class="text-center text-secondary py-5">Teknisyen bulunamadı.</td></tr>';}
// Kullanıcı rolü doğrulandıktan sonra garaj, ekip ve personel verileri paralel yüklenir.
async function initialize(){try{user=await authService.requireAuthenticatedUser();if(!user)return;document.querySelector('#current-user').textContent=`${user.fullName} · ${user.role}`;renderNavigation('technicians',user.role);const garages=await garagesApi.getAll();garages.forEach(g=>{document.querySelector('#garage-filter').appendChild(new Option(`${g.code} · ${g.name}`,g.id));document.querySelector('#create-garage').appendChild(new Option(`${g.code} · ${g.name}`,g.id));});if(user.role!=='Admin'){document.querySelector('#garage-filter').closest('.col-md-6').classList.add('d-none');document.querySelector('#create-garage').value=user.garageId;document.querySelector('#create-garage').disabled=true;}[technicians,teams]=await Promise.all([techniciansApi.getAll(),techniciansApi.getTeams()]);render();document.querySelector('#content').classList.remove('d-none');}catch(error){const box=document.querySelector('#page-error');box.textContent=error.message;box.classList.remove('d-none');}finally{document.querySelector('#loading').classList.add('d-none');}}
document.querySelector('#garage-filter').addEventListener('change',render);document.querySelector('#search').addEventListener('input',render);document.querySelector('#create-button').addEventListener('click',()=>createModal.show());
document.querySelector('#create-form').addEventListener('submit',async event=>{event.preventDefault();const formElement=event.currentTarget;const submitButton=event.submitter??formElement.querySelector('[type="submit"]');const data=Object.fromEntries(new FormData(formElement));data.garageId=Number(user.role==='Admin'?data.garageId:user.garageId);if(submitButton)submitButton.disabled=true;try{const result=await techniciansApi.create(data);createModal.hide();await Swal.fire({icon:'success',title:'Teknisyen eklendi',text:`${result.personnelNumber} · ${result.team}`});[technicians,teams]=await Promise.all([techniciansApi.getAll(),techniciansApi.getTeams()]);render();formElement.reset();}catch(error){await Swal.fire({icon:'error',title:'İşlem başarısız',text:error.message});}finally{if(submitButton)submitButton.disabled=false;}});
document.querySelector('#technician-body').addEventListener('click',async event=>{const button=event.target.closest('[data-toggle]');if(!button)return;try{await techniciansApi.toggleActive(button.dataset.toggle);[technicians,teams]=await Promise.all([techniciansApi.getAll(),techniciansApi.getTeams()]);render();}catch(error){Swal.fire({icon:'error',title:'Durum değiştirilemedi',text:error.message});}});document.querySelector('#logout-button').addEventListener('click',()=>authService.logout());initialize();
