using IettFaultManagement.Api.Data;
using IettFaultManagement.Api.Models.Database;
using Microsoft.EntityFrameworkCore;
namespace IettFaultManagement.Api.Services;
/// <summary>
/// Açık arızaları SLA süresi ve tekrar sıklığı açısından tarar; gerekli uyarı ve
/// bildirimleri tekilleştirerek oluşturur.
/// </summary>
public sealed class FaultMonitoringWorker(IServiceScopeFactory scopes,ILogger<FaultMonitoringWorker> logger):BackgroundService
{
 protected override async Task ExecuteAsync(CancellationToken token){await Task.Delay(TimeSpan.FromSeconds(10),token);/* Kritik araç sağlığı bildirimlerinin kısa sürede ulaşması için tarama 15 saniyede bir yapılır. */using var timer=new PeriodicTimer(TimeSpan.FromSeconds(15));do{try{using var scope=scopes.CreateScope();await ProcessAsync(scope.ServiceProvider.GetRequiredService<ApplicationDbContext>(),scope.ServiceProvider.GetRequiredService<AppNotificationService>(),token);}catch(OperationCanceledException) when(token.IsCancellationRequested){}catch(Exception ex){logger.LogError(ex,"Arıza ve araç sağlığı izleme işlemi çalıştırılamadı.");}}while(await timer.WaitForNextTickAsync(token));}
 private static async Task ProcessAsync(ApplicationDbContext db,AppNotificationService notifications,CancellationToken token){var now=DateTime.UtcNow;await db.Database.ExecuteSqlRawAsync("UPDATE fault_management.faults f SET first_response_at=fa.assigned_at FROM fault_management.fault_assignments fa WHERE fa.fault_id=f.id AND f.first_response_at IS NULL",token);var breached=await db.VwFaultSlaStatuses.AsNoTracking().Where(x=>x.SlaStatus=="BREACHED"||x.SlaStatus=="RESPONSE_BREACHED").ToListAsync(token);foreach(var x in breached)await AlertAsync(db,notifications,x.FaultId,x.GarageId,"SLA_BREACH","SLA süresi aşıldı",$"{x.FaultNumber} numaralı arızanın hedef süresi aşıldı.",now,token);var repeats=await db.VwRecurringVehicleFaults.AsNoTracking().ToListAsync(token);foreach(var repeat in repeats){var latest=await db.Faults.Where(x=>x.VehicleId==repeat.VehicleId&&x.FaultCategoryId==repeat.FaultCategoryId).OrderByDescending(x=>x.OccurredAt).Select(x=>new{x.Id,x.GarageId,x.Vehicle.DoorNumber}).FirstAsync(token);await AlertAsync(db,notifications,latest.Id,latest.GarageId,"RECURRING_FAULT","Tekrarlayan araç arızası",$"{latest.DoorNumber} aracında aynı kategoride {repeat.FaultCount} arıza görüldü.",now,token);}/* Sağlık puanı 50'nin altına düşen araçlar merkez ve ilgili garaj için kritik kabul edilir. */var riskyVehicles=await db.VwVehicleHealthScores.AsNoTracking().Where(x=>x.HealthScore<50).ToListAsync(token);foreach(var vehicle in riskyVehicles){var latestFault=await db.Faults.Where(x=>x.VehicleId==vehicle.VehicleId).OrderByDescending(x=>x.OccurredAt).Select(x=>new{x.Id,x.GarageId,x.Vehicle.DoorNumber,x.Vehicle.Plate}).FirstOrDefaultAsync(token);if(latestFault is null)continue;await AlertAsync(db,notifications,latestFault.Id,latestFault.GarageId,"VEHICLE_HEALTH_CRITICAL","Kritik araç sağlık puanı",$"{latestFault.DoorNumber} ({latestFault.Plate}) aracının sağlık puanı {vehicle.HealthScore}/100 seviyesine düştü. Bu durum sakıncalıdır; araç genel olarak izlenmelidir.",now,token);}await db.SaveChangesAsync(token);}
 private static async Task AlertAsync(ApplicationDbContext db,AppNotificationService notifications,long faultId,long garageId,string type,string title,string message,DateTime now,CancellationToken token){/* Açık alarm aynı olay için bildirim yağmurunu önler. */if(await db.FaultAlerts.AnyAsync(x=>x.FaultId==faultId&&x.AlertType==type&&x.AlertStatus=="OPEN",token))return;db.FaultAlerts.Add(new FaultAlert{FaultId=faultId,AlertType=type,Title=title,Message=message,AlertStatus="OPEN",TriggeredAt=now,CreatedAt=now});if(type=="VEHICLE_HEALTH_CRITICAL"){await notifications.NotifyVehicleHealthRiskAsync(faultId,garageId,title,message,type,now,token);return;}await notifications.NotifyOperationsAsync(faultId,garageId,title,message,type,now,token);}
}
